// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNOJEBJOG8m4ukU6VEhI8G7dSvlWBJkM',
    appId: '1:1022357752343:web:845f269c166d1f568b2a52',
    messagingSenderId: '1022357752343',
    projectId: 'logistics-801b3',
    authDomain: 'logistics-801b3.firebaseapp.com',
    storageBucket: 'logistics-801b3.appspot.com',
    measurementId: 'G-9KQLX68MMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhEwzFwiTVOLYIC76eUBY-1K7qlua5xTA',
    appId: '1:1022357752343:android:92c3a0a6e3f4c71c8b2a52',
    messagingSenderId: '1022357752343',
    projectId: 'logistics-801b3',
    storageBucket: 'logistics-801b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSnXCzjQd7d5PXPn_8uvr5Lmgmog72oIU',
    appId: '1:1022357752343:ios:a947d709346eec448b2a52',
    messagingSenderId: '1022357752343',
    projectId: 'logistics-801b3',
    storageBucket: 'logistics-801b3.appspot.com',
    iosBundleId: 'com.example.logistics',
  );
}
