// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7LklCq-qsKgeKZCNWSbA3gd-lQukvIY',
    appId: '1:783267230560:web:3be7ce404c2bed98422405',
    messagingSenderId: '783267230560',
    projectId: 'alnco-7370c',
    authDomain: 'alnco-7370c.firebaseapp.com',
    storageBucket: 'alnco-7370c.appspot.com',
    measurementId: 'G-M4VT9JDGCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmg-ldfUQk3jDfPuYncw2wtjNb9A780vo',
    appId: '1:783267230560:android:42c03dccc202359d422405',
    messagingSenderId: '783267230560',
    projectId: 'alnco-7370c',
    storageBucket: 'alnco-7370c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAUvG2x9q67gkH5U0_2Zepa12y1l3RecY',
    appId: '1:783267230560:ios:35381680473d10ff422405',
    messagingSenderId: '783267230560',
    projectId: 'alnco-7370c',
    storageBucket: 'alnco-7370c.appspot.com',
    iosBundleId: 'com.example.logistics',
  );

}